# access credentials for twitter

CONSUMER_KEY = 'INSERT YOUR PASSWORD HERE'
CONSUMER_SECRET = 'INSERT YOUR PASSWORD HERE'
ACCESS_TOKEN = 'INSERT YOUR PASSWORD HERE'
ACCESS_TOKEN_SECRET = 'INSERT YOUR PASSWORD HERE'
